services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ameos\Amqp\:
    resource: '../Classes/*'

  messenger.transport.amqp:
    factory: [ '@Ameos\Amqp\Messenger\AmqpTransportFactory', 'createTransportForTypo3' ]
    class: 'Symfony\Component\Messenger\Bridge\Amqp\Transport\AmqpTransport'
    tags:
      - name: 'messenger.sender'
        identifier: 'amqp'
      - name: 'messenger.receiver'
        identifier: 'amqp'